from interpreter import op_dict, op_list
from interpreter.token import Token
from interpreter.lexer import Lexer
from interpreter.syntax_analyser import SyntaxAnalyser
from typing import List, Dict


# Note: Need to add docstrings and comments
# for the Parser class.
class Parser:
    """
        Responsible for consuming the stream of tokens generated
        by the lexer and to evaluate/interpret it to the output to
        be generated by the brainfxck code.

            Attributes:
                token_stream : List[Token]
                    the stream of tokens generated by the lexer.
                tape_size : int
                    the number of blocks in the brainfxck tape.
                    default -> 1000

            Methods:
                parse()
                    evaluates/interprets the token stream.
    """

    def __init__(self, token_stream: List[Token], tape_size: int = 1000) -> None:
        """
            Constructor method to store the token stream as an instance variable.

            Parameters:
                token_stream : List[Token]
                    the stream of tokens generated by the lexer.
                tape_size : int
                    the number of blocks in the brainfxck tape.
                    default -> 1000

            Returns:
                None
        """

        # instance variables such as the input token_stream,
        # tape to actually manipulate the memory, tape_size for
        # the loop, code_size for the loop, and output_string to
        # store the chr value generated by the ascii at the given
        # tape position whenever the OUTPUT operation is called
        self.token_stream = token_stream
        self.tape = [0 for i in range(tape_size)]
        self.tape_size = tape_size
        self.code_size = len(token_stream)
        self.output_string = ""

    def parse(self):
        tape_ptr = 0
        code_ptr = 0
        while(code_ptr < self.code_size):

            # Increments the block at which the tape_ptr is at
            # by one
            if self.token_stream[code_ptr].op_name == op_dict["+"]:
                self.tape[tape_ptr] += 1

            # Decrements the block at which the tape_ptr is at
            # by one
            elif self.token_stream[code_ptr].op_name == op_dict["-"]:
                self.tape[tape_ptr] -= 1

            # Moves the tape_ptr one position to the right
            elif self.token_stream[code_ptr].op_name == op_dict[">"]:
                tape_ptr = (tape_ptr + 1) % self.tape_size

            # Moves the tape_ptr one position to the left
            elif self.token_stream[code_ptr].op_name == op_dict["<"]:
                tape_ptr = (tape_ptr - 1) % self.tape_size

            # Handles user input; takes only the first character
            # of whatever the user inputs
            elif self.token_stream[code_ptr].op_name == op_dict[","]:
                inp = input()
                self.tape[tape_ptr] = ord(inp[0])

            # Handles the output functionality by adding the chr
            # of the ascii at the memory block the tape_ptr is at
            # to the output_string
            elif self.token_stream[code_ptr].op_name == op_dict["."]:
                # print(chr(self.tape[tape_ptr]), end="")
                self.output_string += chr(self.tape[tape_ptr])

            # If the current position of the tape_ptr has zero, then
            # the code_ptr is incremented as long as it does not reach
            # an equivalent (emphasis on equivalent) closing brace
            # Otherwise, the following conditions take place
            elif self.token_stream[code_ptr].op_name == op_dict["["]:
                if self.tape[tape_ptr] == 0:
                    brace_counter = 0
                    code_ptr += 1
                    while(code_ptr < self.code_size):
                        if self.token_stream[code_ptr].op_name == op_dict["]"] and brace_counter == 0:

                            break
                        elif self.token_stream[code_ptr].op_name == op_dict["]"]:
                            brace_counter -= 1
                        elif self.token_stream[code_ptr].op_name == op_dict["["]:
                            brace_counter += 1
                        code_ptr += 1

            # Similar to the open brace scenario but opposite
            elif self.token_stream[code_ptr].op_name == op_dict["]"]:
                if self.tape[tape_ptr] != 0:
                    brace_counter = 0
                    code_ptr -= 1
                    while(code_ptr >= 0):
                        if self.token_stream[code_ptr].op_name == op_dict["["] and brace_counter == 0:
                            break
                        elif self.token_stream[code_ptr].op_name == op_dict["["]:
                            brace_counter -= 1
                        elif self.token_stream[code_ptr].op_name == op_dict["]"]:
                            brace_counter += 1
                        code_ptr -= 1

            code_ptr += 1
        print("")
